language: node_js
dist: trusty
sudo: required
node_js: stable
install:
  - npm install -g yarn
  - yarn global add purescript@^0.12.0 pulp@^12.3.0 bower purescript-psa@^0.6.0
  - export PATH="$PATH:`yarn global bin`"
  - bower install --production
script:
  - pulp build
  - bower install
  - pulp test --include examples
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push
